# Generated by Django 5.2.5 on 2025-08-15 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.driverprofile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_bookings', to='bookings.address'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_bookings', to='bookings.address'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.quote'),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='dropoff_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_dropoffs', to='bookings.address'),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='pickup_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_pickups', to='bookings.address'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'service_tier'], name='bookings_bo_status_b6bd64_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_bo_created_1720a2_idx'),
        ),
    ]
