# Generated by Django 5.2.5 on 2025-08-23 05:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_servicetype_shippingtype_quote_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='shipment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_type', to='bookings.servicetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service_type',
            field=models.ForeignKey(default='standard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='bookings.servicetype'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_type',
            field=models.ForeignKey(default='parcels', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='bookings.shippingtype'),
        ),
    ]
