"""
Django settings for Drop_N_Roll project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

import environ
from celery import Celery
from decouple import config
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DJANGO_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')

# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_seed',

    'bookings.apps.BookingsConfig',
    'users.apps.UsersConfig',
    'tracking.apps.TrackingConfig',
    'driver.apps.DriverConfig',
    'payments.apps.PaymentsConfig',

    'celery',
    'corsheaders',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Drop_N_Roll.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Drop_N_Roll.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'),
        'PORT': env('POSTGRES_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# New: Directory for collected static files
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',  # Optional: Directory for project-specific static files
# ]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "users.User"

# Allow specific origins (e.g., your frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter your token like: Bearer <your_token>",
        }
    },
    "USE_SESSION_AUTH": False,  # Hide Django login in Swagger UI
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CELERY
CELERY_BROKER_URL = env("CELERY_BROKER_URL",
                        default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND",
                            default="redis://localhost:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = env("CELERY_TIMEZONE", default="UTC")

# Email backend
EMAIL_BACKEND = env(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = env("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")

# Urls
FRONTEND_URL = env("FRONTEND_URL")
BACKEND_URL = env("BACKEND_URL", default="http://localhost:8000")

# Google OAuth2 settings
GOOGLE_CLIENT_ID = env("CLIENT_ID")
GOOGLE_CLIENT_SECRET = env("CLIENT_SECRET")

# JWT settings for consistency with existing auth
SOCIAL_AUTH_JSONFIELD_ENABLED = True
SOCIAL_AUTH_USER_MODEL = 'users.User'

# paypal payment
# Use 'https://api-m.paypal.com' for live
PAYPAL_API_URL = env(
    "PAYPAL_API_URL", default='https://api-m.sandbox.paypal.com')
PAYPAL_CLIENT_ID = env("PAYPAL_CLIENT_ID")  # From PayPal Developer Dashboard
# From PayPal Developer Dashboard
PAYPAL_CLIENT_SECRET = env("PAYPAL_CLIENT_SECRET")
# From PayPal Dashboard > Webhooks
PAYPAL_WEBHOOK_ID = env("PAYPAL_WEBHOOK_ID")

PAYPAL_RETURN_URL = env("PAYPAL_RETURN_URL")
PAYPAL_CANCEL_URL = env("PAYPAL_CANCEL_URL")

# ADMIN SITE CUSTOMIZATION SETTINGS WITH UNFOLD
UNFOLD = {
    "SITE_TITLE": "Drop N Roll Administration",
    "SITE_HEADER": 'Drop N Roll',
    # "SITE_SUBHEADER": "Appears under SITE_HEADER",
    "SITE_DROPDOWN": [
        {
            "icon": "diamond",
            "title": _("Drop N Roll"),
            "link": "https://example.com",
        },
        # ...
    ],

    "DASHBOARD_CALLBACK": "Drop_N_Roll.utils.dashboard.dashboard_callback",

    "SITE_URL": "/",
    # "SITE_ICON": lambda request: static("icon.svg"),  # both modes, optimise for 32px height
    # "SITE_ICON": {
    #     "light": lambda request: static("icon-light.svg"),  # light mode
    #     "dark": lambda request: static("icon-dark.svg"),  # dark mode
    # },
    # "SITE_LOGO": lambda request: static("logo.svg"),  # both modes, optimise for 32px height
    # "SITE_LOGO": {
    #     "light": lambda request: static("logo-light.svg"),  # light mode
    #     "dark": lambda request: static("logo-dark.svg"),  # dark mode
    # },
    "SITE_SYMBOL": "speed",  # symbol from icon set
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon.svg"),
        },
    ],
    "SHOW_HISTORY": True,  # show/hide "History" button, default: True
    "SHOW_VIEW_ON_SITE": True,  # show/hide "View on site" button, default: True
    # show/hide "Back" button on changeform in header, default: False
    "SHOW_BACK_BUTTON": False,
    # "ENVIRONMENT": "sample_app.environment_callback", # environment name in header
    # "ENVIRONMENT_TITLE_PREFIX": "sample_app.environment_title_prefix_callback", # environment name prefix in title tag
    # "DASHBOARD_CALLBACK": "sample_app.dashboard_callback",
    "THEME": "light",  # Force theme: "dark" or "light". Will disable theme switcher
    "LOGIN": {
        "image": lambda request: static("sample/login-bg.jpg"),
        # "redirect_after": lambda request: reverse_lazy("admin:APP_MODEL_changelist"),
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },
    "STYLES": [
        lambda request: static("css/style.css"),

        lambda request: static("css/material-icons.css"),

    ],
    "SCRIPTS": [
        lambda request: static("js/script.js"),
    ],
    "BORDER_RADIUS": "6px",
    "COLORS": {
        "base": {
            "50": "255, 255, 255",  # White
            "100": "245, 245, 245",  # Light gray
            "200": "229, 229, 229",  # Lighter gray
            "300": "212, 212, 212",  # Light gray
            "400": "163, 163, 163",  # Medium gray
            "500": "115, 115, 115",  # Gray
            "600": "82, 82, 82",  # Darker gray
            "700": "64, 64, 64",  # Dark gray
            "800": "38, 38, 38",  # Very dark gray
            "900": "23, 23, 23",  # Near black
            "950": "0, 0, 0",  # Black
        },
        "primary": {
            "50": "255, 247, 237",  # Very light orange
            "100": "255, 237, 213",  # Light orange
            "200": "254, 215, 170",  # Lighter orange
            "300": "253, 186, 116",  # Light orange
            "400": "251, 146, 60",  # Medium orange
            "500": "249, 115, 22",  # Orange (#F97316)
            "600": "234, 88, 12",  # Darker orange
            "700": "194, 65, 12",  # Dark orange
            "800": "154, 52, 18",  # Very dark orange
            "900": "124, 45, 18",  # Deep orange
            "950": "67, 20, 7",  # Darkest orange
        },
        "font": {
            "subtle-light": "var(--color-base-400)",  # Medium gray
            "subtle-dark": "var(--color-base-300)",  # Light gray
            "default-light": "var(--color-base-900)",  # Near black
            "default-dark": "var(--color-base-50)",  # White
            "important-light": "var(--color-base-950)",  # Black
            "important-dark": "var(--color-base-50)",  # White
        },
    },
    # "EXTENSIONS": {
    #     "modeltranslation": {
    #         "flags": {
    #             "en": "🇬🇧",
    #             "fr": "🇫🇷",
    #             "nl": "🇧🇪",
    #         },
    #     },
    # },
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "command_search": False,  # Replace the sidebar search with the command search
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Dashboard"),
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "home",  # Material Icon
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ]
            },
            {
                "title": _("Users"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("All Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:users_user_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Customer Profiles"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:users_customerprofile_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Admin Profiles"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:users_adminprofile_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },


                ]
            },
            {
                "title": _("Shipping"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Shipping Types"),
                        "icon": "local_shipping",  # Material Icon
                        "link": reverse_lazy("admin:bookings_shippingtype_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Service Types"),
                        "icon": "category",  # Material Icon
                        "link": reverse_lazy("admin:bookings_servicetype_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Quotes"),
                        "icon": "description",  # Material Icon
                        "link": reverse_lazy("admin:bookings_quote_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Orders"),
                        "icon": "local_shipping",  # Material Icon
                        "link": reverse_lazy("admin:bookings_booking_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Drivers"),  # Parent item for submenu
                "icon": "directions_car",  # Valid Material Icon
                "link": "",  # Empty link for non-clickable parent
                "separator": True,
                "collapsible": True,
                "items": [  # Nested sub-items (submenu)
                    {
                        "title": _("Profile"),
                        "icon": "person",
                        "link": reverse_lazy("admin:driver_driverprofile_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Document"),
                        "icon": "document_search",
                        "link": reverse_lazy("admin:driver_driverdocument_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Availability"),
                        "icon": "do_not_disturb_off",
                        "link": reverse_lazy("admin:driver_driveravailability_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Payout"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:driver_driverpayout_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Ratings"),
                        "icon": "reviews",
                        "link": reverse_lazy("admin:driver_driverrating_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Invite"),
                        "icon": "add",
                        "link": reverse_lazy("admin:driver_driverinvite_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },

                ],
            },

        ],

    },

    # "TABS": [
    #     {
    #         "models": [
    #             "app_label.model_name_in_lowercase",
    #         ],
    #         "items": [
    #             {
    #                 "title": _("Your custom title"),
    #                 "link": reverse_lazy("admin:app_label_model_name_changelist"),
    #                 "permission": "sample_app.permission_callback",
    #             },
    #         ],
    #     },
    # ],
}


def environment_callback(request):
    """
    Callback has to return a list of two values represeting text value and the color
    type of the label displayed in top right corner.
    """
    return ["Production", "danger"]  # info, danger, warning, success


def badge_callback(request):
    return 3

# def permission_callback(request):
#     return request.user.has_perm("sample_app.change_model")
